name: push
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '0 0 */1 * *'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: stefanprodan/alpine-base
          add_git_labels: true
          tags: latest
